import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';

(async () => {
  console.log('Starting Playwright recording...');

  // Launch the browser
  const browser = await chromium.launch({ headless: true });

  const videoDir = path.resolve('./public/projects/allen-estates');

  // Create a new context with video recording enabled
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    recordVideo: {
      dir: videoDir,
      size: { width: 1440, height: 900 }
    }
  });

  const page = await context.newPage();

  console.log('Navigating to homepage...');
  // Go to the website and wait for the network to be mostly idle
  await page.goto('https://allenestates.vizonos.com', { waitUntil: 'networkidle' });

  // Wait 2 seconds to allow the initial hero animations to play out
  await page.waitForTimeout(2000);

  console.log('Scrolling down the page slowly...');

  // Calculate total height to scroll
  const { pageHeight, viewportHeight } = await page.evaluate(() => {
    return {
      pageHeight: document.body.scrollHeight,
      viewportHeight: window.innerHeight
    };
  });

  // Scroll loop parameters
  let currentPosition = 0;
  const scrollStep = 15; // Pixels to scroll each step
  const scrollDelay = 20; // Milliseconds between scrolls (creates a smooth, cinematic pan)

  // Execute the scroll
  while (currentPosition + viewportHeight < pageHeight) {
    currentPosition += scrollStep;
    await page.evaluate((pos) => window.scrollTo(0, pos), currentPosition);
    await page.waitForTimeout(scrollDelay);
  }

  // Rest at the bottom for 1 second
  await page.waitForTimeout(1000);

  // Get the temporary video path generated by Playwright
  const videoPath = await page.video().path();

  console.log('Closing browser and finalizing video...');
  await context.close();
  await browser.close();

  // Rename the file to a predictable, clean name
  const finalPath = path.join(videoDir, 'home-scroll.webm');

  // Overwrite if it already exists
  if (fs.existsSync(finalPath)) {
    fs.unlinkSync(finalPath);
  }
  fs.renameSync(videoPath, finalPath);

  console.log(`✅ Video successfully saved to: ${finalPath}`);
})().catch(console.error);
